language: node_js
node_js:
  - 0.8
install:
  - "npm i coffee-script"
  - "npm i ."
  - "git submodule update --init"
script: "./development --build"
after_script:
  - "tar tvfz build.tar.gz"
notifications:
  email: false
